### ISSUE TITLE
Robust perf measurements

### ISSUE THREAD

**Issue by bennn** [utahplt/static-python-perf#5]
We need a good way to measure the running time of Python programs.

In the past, I'd run a program 10 times or so and take the mean. This is fragile. If there are some really-fast or really-slow numbers, for whatever reason, then the mean gets thrown off.

A better way would be to use nonparametric confidence intervals and run until convergence. Then we could say:

- "We ran the program until the 95% confidence interval was within 10% of the sample mean."

Tasks:
- Research nonparametric confidence intervals, figure out how to compute them & how to compare to a mean.
- Find/make a simple Python program to run
- How many runs do we need for the program to converge?
- How many runs do the benchmarks need?

@vivaan2006 @crypticnumbers8 one of you please take the lead on this.

**Comment by CrypticNumbers8** [comment]
Hi Professor, I will work on this over the weekend!

**Comment by bennn** [comment]
Notes from email:

```
=== Vivaan ===
Regarding Issue #5, were you thinking of using the time (maybe even timeit) module like some of the benchmarks initially had? I was thinking Numpy and Sklearn could help with the np confidence intervals, article below gives some information about the bootstrap method, we could maybe use some of the bootstrap scripts from there if possible (look at 1.A.0). Honestly, for a sample program, a simple sorting algorithm would do, but it wouldn't matter too much ideally. For finding the runs for the program to converge, we could set an initial loop variable that keeps track of the number of times our program runs, we could maybe just start off with 100, and plot that so finding convergence would be slightly easier. As for the number of runs the benchmark needs, what if we used a loop again and increase the number of times we run the program, and measure the confidence interval each time, once the interval becomes 10% from the mean (I think it was 10%..) the program stops? I'm aware this is a more simplified version of what we will end up doing, but I felt that laying out everything I know would make it better. Also, I'd have to look a lot more into it! especially because I don't have exact numbers, but I hope this was a semi-decent start.https://aegis4048.github.io/non-parametric-confidence-interval-with-bootstrap-


=== Ben ===
Fantastic start yes!!!

Any timer works. I would use the old one, yes. The important thing is
that it measures ONLY the call to the main function. Any setup that
happens beforehand ... like reading in data files ... cannot be part
of the time.

This paper has examples of what not to measure:
<https://users.cs.northwestern.edu/~robby/courses/322-2013-spring/mytkowicz-wrong-data.pdf>

Sorting algorithm is fine for the first program.

Definitely use a loop. Keep going until it's "stable".

10% is a loose number. We can change it based on the data. (If we
increase it, then we'll need fewer runs but it's less certain that our
measurements capture the "actual" mean if we were to run millions of
times.)

=== Vivaan ===
Thanks! For excluding the setup time, we could do a simple time.time(), and I'm pretty sure that it excludes any setup time.

For only running the main function, we could do an if statement and say if the function name is __main__ (seen in some benchmarks before) it computes the time.time(). 

Just a side thought in the conditional if we decide to use it, would we be doing the end time minus the start time for finding the runtime? 

For measuring the stability of the loop could we have some sort of conditions, say if the values go out of a certain range, or the standard deviation goes significantly off, we could terminate the program? 

Regarding the 10% being a loose number, how do you think we vary that depending on the data, I know you can set an initial value, but I'm not sure how it can be data-dependent. 

=== Ben ===
Take a look at the old Timer from the retic_performance repo. It does
the end-minus-start and lets you decide where to measure.

Next step is to test a few programs and see how long they take to
converge. If it's +1000 runs, then we can loosen the 10% number.
```

**Comment by bennn** [comment]
1. Get a sequence of 8 numbers from a Numpy normal distrubution with mean 10
2. Compute 95% confidence interval for the 8 numbers
3. Compute sample mean for the 8 numbers
4. Compute a 10% interval of the sample mean (mean + 10%, mean - 10%)
5. Check if  the CI interval is within the 10% interval

Try with uniform too. It should not converge even with 5000 runs!

How long does normal take to converge?

**Comment by bennn** [comment]
@vivaan2006 we skipped an important word last meeting: "nonparametric"

Please research nonparatetric confidence intervals. Do we want these for performance numbers?

**Comment by vivaan2006** [comment]
just pushed some code that does something along those lines, I tried using the Bootstrap method as mentioned a few weeks ago, but I'm not too sure if it is correct. Feel free to take a look.

**Comment by bennn** [comment]
Fixed by Vivaan long ago, closing!

This 2010 paper (with many supporting references) says, however, that parametric stats are often robust. We should be careful about jumping ship 100% to the non-parametric world:
https://link.springer.com/article/10.1007/s10459-010-9222-y
